/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesRideRouteImport } from './routes/services.ride'
import { Route as ServicesPadalaRouteImport } from './routes/services.padala'
import { Route as ServicesPabiliRouteImport } from './routes/services.pabili'
import { Route as ServicesFoodRouteImport } from './routes/services.food'
import { Route as DriverWalletRouteImport } from './routes/driver.wallet'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminRiderFinanceRouteImport } from './routes/admin.rider-finance'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as ServicesFoodManualRouteImport } from './routes/services.food.manual'
import { Route as ServicesFoodCartRouteImport } from './routes/services.food.cart'
import { Route as ServicesFoodRestaurantIdRouteImport } from './routes/services.food.$restaurantId'
import { Route as CheckoutOrderIdSuccessRouteImport } from './routes/checkout.$orderId.success'
import { Route as CheckoutOrderIdPayRouteImport } from './routes/checkout.$orderId.pay'
import { Route as CheckoutOrderIdFailedRouteImport } from './routes/checkout.$orderId.failed'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRideRoute = ServicesRideRouteImport.update({
  id: '/services/ride',
  path: '/services/ride',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPadalaRoute = ServicesPadalaRouteImport.update({
  id: '/services/padala',
  path: '/services/padala',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPabiliRoute = ServicesPabiliRouteImport.update({
  id: '/services/pabili',
  path: '/services/pabili',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFoodRoute = ServicesFoodRouteImport.update({
  id: '/services/food',
  path: '/services/food',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverWalletRoute = DriverWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DriverRoute,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiderFinanceRoute = AdminRiderFinanceRouteImport.update({
  id: '/rider-finance',
  path: '/rider-finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesFoodManualRoute = ServicesFoodManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => ServicesFoodRoute,
} as any)
const ServicesFoodCartRoute = ServicesFoodCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ServicesFoodRoute,
} as any)
const ServicesFoodRestaurantIdRoute =
  ServicesFoodRestaurantIdRouteImport.update({
    id: '/$restaurantId',
    path: '/$restaurantId',
    getParentRoute: () => ServicesFoodRoute,
  } as any)
const CheckoutOrderIdSuccessRoute = CheckoutOrderIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutOrderIdRoute,
} as any)
const CheckoutOrderIdPayRoute = CheckoutOrderIdPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => CheckoutOrderIdRoute,
} as any)
const CheckoutOrderIdFailedRoute = CheckoutOrderIdFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => CheckoutOrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRouteWithChildren
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/rider-finance': typeof AdminRiderFinanceRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRouteWithChildren
  '/driver/wallet': typeof DriverWalletRoute
  '/services/food': typeof ServicesFoodRouteWithChildren
  '/services/pabili': typeof ServicesPabiliRoute
  '/services/padala': typeof ServicesPadalaRoute
  '/services/ride': typeof ServicesRideRoute
  '/checkout/$orderId/failed': typeof CheckoutOrderIdFailedRoute
  '/checkout/$orderId/pay': typeof CheckoutOrderIdPayRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/services/food/$restaurantId': typeof ServicesFoodRestaurantIdRoute
  '/services/food/cart': typeof ServicesFoodCartRoute
  '/services/food/manual': typeof ServicesFoodManualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRouteWithChildren
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/rider-finance': typeof AdminRiderFinanceRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRouteWithChildren
  '/driver/wallet': typeof DriverWalletRoute
  '/services/food': typeof ServicesFoodRouteWithChildren
  '/services/pabili': typeof ServicesPabiliRoute
  '/services/padala': typeof ServicesPadalaRoute
  '/services/ride': typeof ServicesRideRoute
  '/checkout/$orderId/failed': typeof CheckoutOrderIdFailedRoute
  '/checkout/$orderId/pay': typeof CheckoutOrderIdPayRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/services/food/$restaurantId': typeof ServicesFoodRestaurantIdRoute
  '/services/food/cart': typeof ServicesFoodCartRoute
  '/services/food/manual': typeof ServicesFoodManualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRouteWithChildren
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/rider-finance': typeof AdminRiderFinanceRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRouteWithChildren
  '/driver/wallet': typeof DriverWalletRoute
  '/services/food': typeof ServicesFoodRouteWithChildren
  '/services/pabili': typeof ServicesPabiliRoute
  '/services/padala': typeof ServicesPadalaRoute
  '/services/ride': typeof ServicesRideRoute
  '/checkout/$orderId/failed': typeof CheckoutOrderIdFailedRoute
  '/checkout/$orderId/pay': typeof CheckoutOrderIdPayRoute
  '/checkout/$orderId/success': typeof CheckoutOrderIdSuccessRoute
  '/services/food/$restaurantId': typeof ServicesFoodRestaurantIdRoute
  '/services/food/cart': typeof ServicesFoodCartRoute
  '/services/food/manual': typeof ServicesFoodManualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/driver'
    | '/orders'
    | '/privacy'
    | '/admin/finance'
    | '/admin/restaurants'
    | '/admin/rider-finance'
    | '/admin/wallet'
    | '/checkout/$orderId'
    | '/driver/wallet'
    | '/services/food'
    | '/services/pabili'
    | '/services/padala'
    | '/services/ride'
    | '/checkout/$orderId/failed'
    | '/checkout/$orderId/pay'
    | '/checkout/$orderId/success'
    | '/services/food/$restaurantId'
    | '/services/food/cart'
    | '/services/food/manual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/driver'
    | '/orders'
    | '/privacy'
    | '/admin/finance'
    | '/admin/restaurants'
    | '/admin/rider-finance'
    | '/admin/wallet'
    | '/checkout/$orderId'
    | '/driver/wallet'
    | '/services/food'
    | '/services/pabili'
    | '/services/padala'
    | '/services/ride'
    | '/checkout/$orderId/failed'
    | '/checkout/$orderId/pay'
    | '/checkout/$orderId/success'
    | '/services/food/$restaurantId'
    | '/services/food/cart'
    | '/services/food/manual'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/driver'
    | '/orders'
    | '/privacy'
    | '/admin/finance'
    | '/admin/restaurants'
    | '/admin/rider-finance'
    | '/admin/wallet'
    | '/checkout/$orderId'
    | '/driver/wallet'
    | '/services/food'
    | '/services/pabili'
    | '/services/padala'
    | '/services/ride'
    | '/checkout/$orderId/failed'
    | '/checkout/$orderId/pay'
    | '/checkout/$orderId/success'
    | '/services/food/$restaurantId'
    | '/services/food/cart'
    | '/services/food/manual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DriverRoute: typeof DriverRouteWithChildren
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRouteWithChildren
  ServicesFoodRoute: typeof ServicesFoodRouteWithChildren
  ServicesPabiliRoute: typeof ServicesPabiliRoute
  ServicesPadalaRoute: typeof ServicesPadalaRoute
  ServicesRideRoute: typeof ServicesRideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ride': {
      id: '/services/ride'
      path: '/services/ride'
      fullPath: '/services/ride'
      preLoaderRoute: typeof ServicesRideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/padala': {
      id: '/services/padala'
      path: '/services/padala'
      fullPath: '/services/padala'
      preLoaderRoute: typeof ServicesPadalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/pabili': {
      id: '/services/pabili'
      path: '/services/pabili'
      fullPath: '/services/pabili'
      preLoaderRoute: typeof ServicesPabiliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/food': {
      id: '/services/food'
      path: '/services/food'
      fullPath: '/services/food'
      preLoaderRoute: typeof ServicesFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/wallet': {
      id: '/driver/wallet'
      path: '/wallet'
      fullPath: '/driver/wallet'
      preLoaderRoute: typeof DriverWalletRouteImport
      parentRoute: typeof DriverRoute
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rider-finance': {
      id: '/admin/rider-finance'
      path: '/rider-finance'
      fullPath: '/admin/rider-finance'
      preLoaderRoute: typeof AdminRiderFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/food/manual': {
      id: '/services/food/manual'
      path: '/manual'
      fullPath: '/services/food/manual'
      preLoaderRoute: typeof ServicesFoodManualRouteImport
      parentRoute: typeof ServicesFoodRoute
    }
    '/services/food/cart': {
      id: '/services/food/cart'
      path: '/cart'
      fullPath: '/services/food/cart'
      preLoaderRoute: typeof ServicesFoodCartRouteImport
      parentRoute: typeof ServicesFoodRoute
    }
    '/services/food/$restaurantId': {
      id: '/services/food/$restaurantId'
      path: '/$restaurantId'
      fullPath: '/services/food/$restaurantId'
      preLoaderRoute: typeof ServicesFoodRestaurantIdRouteImport
      parentRoute: typeof ServicesFoodRoute
    }
    '/checkout/$orderId/success': {
      id: '/checkout/$orderId/success'
      path: '/success'
      fullPath: '/checkout/$orderId/success'
      preLoaderRoute: typeof CheckoutOrderIdSuccessRouteImport
      parentRoute: typeof CheckoutOrderIdRoute
    }
    '/checkout/$orderId/pay': {
      id: '/checkout/$orderId/pay'
      path: '/pay'
      fullPath: '/checkout/$orderId/pay'
      preLoaderRoute: typeof CheckoutOrderIdPayRouteImport
      parentRoute: typeof CheckoutOrderIdRoute
    }
    '/checkout/$orderId/failed': {
      id: '/checkout/$orderId/failed'
      path: '/failed'
      fullPath: '/checkout/$orderId/failed'
      preLoaderRoute: typeof CheckoutOrderIdFailedRouteImport
      parentRoute: typeof CheckoutOrderIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminRiderFinanceRoute: typeof AdminRiderFinanceRoute
  AdminWalletRoute: typeof AdminWalletRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFinanceRoute: AdminFinanceRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminRiderFinanceRoute: AdminRiderFinanceRoute,
  AdminWalletRoute: AdminWalletRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DriverRouteChildren {
  DriverWalletRoute: typeof DriverWalletRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverWalletRoute: DriverWalletRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface CheckoutOrderIdRouteChildren {
  CheckoutOrderIdFailedRoute: typeof CheckoutOrderIdFailedRoute
  CheckoutOrderIdPayRoute: typeof CheckoutOrderIdPayRoute
  CheckoutOrderIdSuccessRoute: typeof CheckoutOrderIdSuccessRoute
}

const CheckoutOrderIdRouteChildren: CheckoutOrderIdRouteChildren = {
  CheckoutOrderIdFailedRoute: CheckoutOrderIdFailedRoute,
  CheckoutOrderIdPayRoute: CheckoutOrderIdPayRoute,
  CheckoutOrderIdSuccessRoute: CheckoutOrderIdSuccessRoute,
}

const CheckoutOrderIdRouteWithChildren = CheckoutOrderIdRoute._addFileChildren(
  CheckoutOrderIdRouteChildren,
)

interface ServicesFoodRouteChildren {
  ServicesFoodRestaurantIdRoute: typeof ServicesFoodRestaurantIdRoute
  ServicesFoodCartRoute: typeof ServicesFoodCartRoute
  ServicesFoodManualRoute: typeof ServicesFoodManualRoute
}

const ServicesFoodRouteChildren: ServicesFoodRouteChildren = {
  ServicesFoodRestaurantIdRoute: ServicesFoodRestaurantIdRoute,
  ServicesFoodCartRoute: ServicesFoodCartRoute,
  ServicesFoodManualRoute: ServicesFoodManualRoute,
}

const ServicesFoodRouteWithChildren = ServicesFoodRoute._addFileChildren(
  ServicesFoodRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DriverRoute: DriverRouteWithChildren,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRouteWithChildren,
  ServicesFoodRoute: ServicesFoodRouteWithChildren,
  ServicesPabiliRoute: ServicesPabiliRoute,
  ServicesPadalaRoute: ServicesPadalaRoute,
  ServicesRideRoute: ServicesRideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
